WRITER_01:
  ADDRESS: [127.0.0.1]
  PORT: 1025
  FRAGMENT_SIZE: 1200               # in B
  DEADLINE: 100000                  # in us
  SHAPING_TIME: 2000                # in us
  NACK_SUPPRESSION_DURATION: 5000   # in us
  SIZE_CACHE: 2
  UUID: 0
  PRIO_MODE : 0
  READERS: ["READER_01"]
  
READER_01:
  ADDRESS: 127.0.0.1
  PORT: 1024
  DEADLINE: 100000                  # in us
  RESPONSE_DELAY: 500               # in us
  DEADLINE: 100000                  # in us
  SIZE_CACHE: 2
  UUID: 0
  PRIORITY : 0
  WRITER: ["WRITER_01"]