WRITER_01:
  ADDRESS: 127.0.0.1
  PORT: 50001
  FRAGMENT_SIZE: 5                  # in B
  DEADLINE: 5000000                 # in us
  SHAPING_TIME: 1000000             # in us
  NACK_SUPPRESSION_DURATION: 20000  # in us
  TIMEOUT: 20000                    # in us
  SIZE_CACHE: 2
  PRIO_MODE : 3
  READERS: [READER_01]
  HOST: TELEMETRY
  
READER_01:
  ADDRESS: 127.0.0.1
  PORT: 50000
  DEADLINE: 5000000                 # in us
  RESPONSE_DELAY: 500               # in us
  SIZE_CACHE: 2
  PRIORITY : 0
  WRITER: WRITER_01
  HOST: CLIENT2